version: "3.8"

services:
  antigavity-openai-adapter:
    image: antigravity-openai-adapter:latest
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Host for both API (OpenAI) and WebUI (via transparent proxy)
        - "traefik.http.routers.antigravity-openai-adapter.rule=Host(`antigravity.pedrofarias.cloudns.be`)"
        - "traefik.http.routers.antigravity-openai-adapter.entrypoints=websecure"
        - "traefik.http.routers.antigravity-openai-adapter.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.antigravity-openai-adapter.loadbalancer.server.port=8081"

    environment:
      - NODE_ENV=production
      - PORT=8081
      - UPSTREAM_URL=http://localhost:8080
      - AUTO_START_PROXY=true
      - API_KEY=pedrofariasx
      - UPSTREAM_API_KEY=test
      - DEBUG=true

    networks:
      - rede_interna

    volumes:
      - antigravity_data:/root/

volumes:
  antigravity_data:

networks:
  rede_interna:
    external: true
